# Name of workflow
name: Hexlet CI

# Trigger the workflow on push or pull request
on:
  - push

jobs:
  build: # имя взято для примера
    runs-on: ubuntu-latest

    steps:
      # Клонируем репозиторий
      - uses: actions/checkout@v3
      # Устанавливаем Node.js
      - uses: actions/setup-node@v3
      # Ставим зависимости
      - run: install build
      - run: make start
      # Запускаем линтер
      - run: make test
      # Запускаем тесты
      # у шагов может быть имя, иногда это помогает отладке
      # имя выводится на Github при просмотре сборки
      - name: run lint

